### ISSUE TITLE
Remove positive comments

### ISSUE THREAD

**Issue by alienxp03** [kfit-dev/pr-size-notifier#2]
https://github.com/kfit-dev/pr-size-notifier/blob/448f041389be32ff3589ababce6af9f6c3dcd24f/entrypoint.sh#L32

- Based on our current flow, it might be better if we only post comment if the test fail.
- Although we are deleting the old comment, we still still get email notifications and it doesn't seems to be necessary.

**Comment by NavindrenBaskaran** [comment]
Done @alienxp03
